#!/usr/bin/env bash

spaces (){
    ACTIVE=$(hyprctl monitors -j | jq '.[] | select(.focused) .activeWorkspace.id')
    hyprctl workspaces -j | jq -r "map({id: .id, active: (.id | . == ${ACTIVE})}) | sort_by(.id) | tostring"
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
